
name: hello world

on:
  push:
    branches:
    - main
  pull_request:
    - main
  workflow_dispatch

jobs:
  hello:
    runs-on: macos-latest
    steps:
      - name: hello world
        shell: bash
        run: echo "hello world"
  goodbye:
    runs-on: macos-latest
    steps:
    - name: goodbye
      shell: bash
      run: echo "goodbye"
