name: hello world workflow
on:
push:
branches:
- main
pull_request:
branches:
- main
workflow_dispatch:

jobs:
hello:
runs-on: macos
steps:
- name: hello world
- run: echo "hello world"
- shell: bash

goodbye:
runs-on: macos
steps:
- run echo "goodbye"
- shell: bash
